name: Cargo Build, Test, and Linting

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_release:
    name: Build project in release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - name: Export executable
        uses: actions/upload-artifact@v4
        with:
          name: pumpkin-${{ matrix.os }}
          compression-level: 9
          path: target/${{ matrix.target }}/release/pumpkin*

